INFO:root:Reading config file.
INFO:root:Loading API.
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/Users/leonardoalchieri/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leonardoalchieri/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leonardoalchieri/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leonardoalchieri/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/Users/leonardoalchieri/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest?key=AIzaSyCsrmsqo2T1Q3dak0-I1e1Pz3433g4iIhg
INFO:root:Loaded API.
INFO:root:Progress region US: 0.0%
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&publishedAfter=2017-11-10T00%3A00%3A00Z&publishedBefore=2018-05-17T00%3A00%3A00Z&regionCode=US&fields=items%2Fid%2FvideoId%2CnextPageToken&videoCategoryId=2&key=AIzaSyCsrmsqo2T1Q3dak0-I1e1Pz3433g4iIhg&alt=json
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&publishedAfter=2017-11-10T00%3A00%3A00Z&publishedBefore=2018-05-17T00%3A00%3A00Z&pageToken=CDIQAA&regionCode=US&fields=items%2Fid%2FvideoId%2CnextPageToken&videoCategoryId=2&key=AIzaSyCsrmsqo2T1Q3dak0-I1e1Pz3433g4iIhg&alt=json
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&publishedAfter=2017-11-10T00%3A00%3A00Z&publishedBefore=2018-05-17T00%3A00%3A00Z&pageToken=CGQQAA&regionCode=US&fields=items%2Fid%2FvideoId%2CnextPageToken&videoCategoryId=2&key=AIzaSyCsrmsqo2T1Q3dak0-I1e1Pz3433g4iIhg&alt=json
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&publishedAfter=2017-11-10T00%3A00%3A00Z&publishedBefore=2018-05-17T00%3A00%3A00Z&pageToken=CJYBEAA&regionCode=US&fields=items%2Fid%2FvideoId%2CnextPageToken&videoCategoryId=2&key=AIzaSyCsrmsqo2T1Q3dak0-I1e1Pz3433g4iIhg&alt=json
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&publishedAfter=2017-11-10T00%3A00%3A00Z&publishedBefore=2018-05-17T00%3A00%3A00Z&pageToken=CMgBEAA&regionCode=US&fields=items%2Fid%2FvideoId%2CnextPageToken&videoCategoryId=2&key=AIzaSyCsrmsqo2T1Q3dak0-I1e1Pz3433g4iIhg&alt=json
WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "quotaExceeded"
INFO:root:Process stopped early
INFO:root:Data saved successfully
